### ISSUE TITLE
Convert Working Sessions PoC into separate markdown pages

### ISSUE THREAD

**Issue by DinisCruz** [project-cx/pbx-group-security#291]
![image](https://user-images.githubusercontent.com/656739/35283759-ff3b9eaa-0050-11e8-9b66-f804a61045c9.png)

![image](https://user-images.githubusercontent.com/656739/35283767-05248642-0051-11e8-9f55-4d52ccc7dd83.png)

**Comment by regisphilibert** [comment]
Wrapping my mind around this issue.

The different markdowns you want is for the events displayed on the page.
Then from the template of the "working-sessions" page we would fetch those individual markdowns to retrieve information about the event (Day, month etc...)
There is several approach to this:

**1/ The old hack:**
Creating different sections beneath "working-sesssions" and loop on those.
The problem is that Hugo will create a page with a url for each of those "dates". If you need a single standalone page for each of those sessions this would be the way to go.

**2/ Data Template:**
https://gohugo.io/templates/data-templates/
Content manager can manage data files stored in directories. 
Jemma here, would create at hugo root data/sessions/6-february.yaml 
I don't think it would be that efficient if those sessions are only going to be used for this one page, but if they were to be used in different places, that is the way to go.

**3/ Page Resources**
Yeah! Based on the idea, that only the "working-sessions" page needs those, it's the best way to go. Jemma just drops some mardown files inside the working-sessions's page bundle. I can easily find them and use their own front-matter to build the date card and more.
**WARNING:** We would need to upgrade hugo version to 0.33 at minimum. Easily done with netlify, but you may have your reason not to.

You're pick. Personally I'm a fan of Page Resources but you know that.

**Comment by regisphilibert** [comment]
@DinisCruz @JemmaDSmith ?

**Comment by JemmaDSmith** [comment]
Do we need separate markdown pages? This is another step in registering surely? Can we not link to the eventbrite pages?

**Comment by regisphilibert** [comment]
I don't need seperate markdown pages, hence my question.

But ideally, we'd build those calendar snippets in html and use the link provided in the Front Matter as the exemple provided.
This is to avoid you having to create a new "calendar card" image everytime you edit/create an event. We would built it in html/css.

You could either use a shortcode in the markdown to call for this iteration over the "calendar cards" or the working session page could have its own layout/template. 
With the latter you wouldn't need a shortcode, the "calendar cards" would just be displayed before or after the markdown content.

Let me know what you think

**Comment by JemmaDSmith** [comment]
what do you need me to do? Not technical at all, so in idiot proof would be great

**Comment by regisphilibert** [comment]
Sorry, my request may not have been clear.

I just need your input as an editor.

I don't have the bigger picture here, so I just need to understand your needs as an editor for this feature. The screenshots didn't cut it for me.

1/ Will those cards only be listed on the Working Sessions page ?
2/ What information about them do you need to be able to manage beside Day, Month, Year, Eventbride link
3/ Do you need standalone pages for them (apparently not)
4/ Anything I didn't think about you may need?
5/ Do you have some PSDs for me to build the cards when we pick a direction.

I personally think the Front Matter option from my initial comment is the way to go, but again, I don't have the big picture and don't want to implement something that won't work for you.

You're my end user. I'm listening.

**Comment by JemmaDSmith** [comment]
1/ Will those cards only be listed on the Working Sessions page ? Yes
2/ What information about them do you need to be able to manage beside Day, Month, Year, Eventbride link? None
3/ Do you need standalone pages for them (apparently not)? I think this can be managed in EventBrite, adding them is a barrier to conversion and a duplication of work
5/ Do you have some PSDs for me to build the cards when we pick a direction? I can get them made

**Comment by regisphilibert** [comment]
Thanks, then Front Matter is the way to go.
1/ I will build the shortcode (so we can have it in any section on the page) and for style will use the screenshot provided so we don't lose too much time waiting for PSDs. If they need too much refine, I may request a PSD.
2/ I will grab what you already added to the markdown and convert it to the Front Matter solution so the page should look ready when I'm done.
Will PR.

For later use, you could use the shortcode on anypage if the Front Matter object is defined.

Thanks @JemmaDSmith !

**Comment by JemmaDSmith** [comment]
PSD with you

**Comment by regisphilibert** [comment]
@JemmaDSmith 
I used the fonts available on the site

- see https://github.com/project-cx/pbx-group-security/pull/292 **for screenshots**.
- See https://raw.githubusercontent.com/regisphilibert/pbx-group-security/events-cards/content/page/working-sessions.md **for Front Matter / shorcode usage **

**Comment by regisphilibert** [comment]
Date format matters: 
**2018-02-20** (we need those leading zeros)

**Comment by DinisCruz** [comment]
Great threat :+1:

I just merged the PR
